version: "0.1"
services:
  influxdb:
    image: influxdb:2.6.1-alpine
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=Netpresso
      - DOCKER_INFLUXDB_INIT_BUCKET=speed-test-metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin-token
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  speedtest:
    build:
      context: ./speed-test/client
      dockerfile: Dockerfile
    container_name: speed-test
    restart: always
    depends_on:
      - influxdb
    links:
      - "influxdb"

  packetserver:
    build:
      context: ./packet_server
      dockerfile: Dockerfile
    container_name: packet-server
    restart: always
    ports:
      - '5000:5000'

  web:
    image: netpresso/netpresso-ui@sha256:0fea5ae7816050a718cd33eb5cfe6fef7218926c2aeb84a092cfe6e60860ce6c
    container_name: web-ui
    restart: always
    depends_on:
      - influxdb
      - speedtest
    ports:
      - "3000:3000"
    links:
      - "influxdb"
      - "speedtest"
      - "packetserver"

volumes:
  influxdb_data: {}