name: Docker Build Test

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build speed-test Docker image
      run: docker build . --file Dockerfile --tag netpresso/netpresso-core:test$(date +%s)
